//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnetchallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        public string Id { get; set; }
        public string NombreCliente { get; set; }
        public int TipoAtencionId { get; set; }
        public string CodigoTipo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual TipoAtencion TipoAtencion { get; set; }
    }
}
